"""
Django settings for delivery_management project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['junaiddo.pythonanywhere.com','do.junaidworld.com','*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',  # For Excel import/export in admin
    'orders',
    'widget_tweaks',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'delivery_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'delivery_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'hrmoule'),
#         'USER': os.environ.get('DB_USER', 'postgres'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
#         'HOST': os.environ.get('DB_HOST', 'localhost'),
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,  # seconds
        },
    }
}
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dubai'

USE_I18N = True
USE_TZ = True


WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = '623707730818076'

# Daily Reports Configuration
DAILY_REPORTS_FOLDER = os.path.join(BASE_DIR, 'delivery_management', 'reports')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/



STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/var/www/delivery_management/media'
MEDIA_URL = '/media/'

STATIC_ROOT = '/var/www/delivery_management/static'
STATIC_URL = '/static/'


# SAP API Sync Configuration
SOURCE_API_URL = os.environ.get('SOURCE_API_URL', 'http://192.168.1.103/IntegrationApi/api/DeliveryOrder')
API_TIMEOUT = int(os.environ.get('API_TIMEOUT', 30))
VPS_API_KEY = os.environ.get('VPS_API_KEY', 'production')
SYNC_DAYS_BACK = int(os.environ.get('SYNC_DAYS_BACK', 3))
# VPS receive URL (will be constructed automatically if not set)
VPS_RECEIVE_URL = os.environ.get('VPS_RECEIVE_URL', None)

# Create logs directory if it doesn't exist (BEFORE logging configuration)
LOG_DIR = BASE_DIR / "logs"
try:
    LOG_DIR.mkdir(exist_ok=True)
    # Ensure the directory is writable
    sync_log_path = LOG_DIR / "sync.log"
    if not sync_log_path.exists():
        sync_log_path.touch()
except (OSError, PermissionError):
    # If we can't create the directory, we'll use console logging only
    pass

# Build handlers dynamically based on what's available
handlers = {
    "console": {
        "level": "INFO",
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    },
}

# Try to add file handlers if directories are writable
try:
    errors_log_path = BASE_DIR / "errors.log"
    handlers["file"] = {
        "level": "ERROR",
        "class": "logging.FileHandler",
        "filename": str(errors_log_path),
    }
except Exception:
    pass

try:
    sync_log_path = LOG_DIR / "sync.log"
    # Test if we can write to this path
    handlers["sync_file"] = {
        "level": "INFO",
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(sync_log_path),
        "maxBytes": 10 * 1024 * 1024,  # 10MB
        "backupCount": 5,
        "formatter": "verbose",
    }
except Exception:
    # If sync_file handler can't be created, use console only
    pass

try:
    whatsapp_log_path = LOG_DIR / "whatsapp.log"
    # Test if we can write to this path
    handlers["whatsapp_file"] = {
        "level": "INFO",
        "class": "logging.handlers.RotatingFileHandler",
        "filename": str(whatsapp_log_path),
        "maxBytes": 10 * 1024 * 1024,  # 10MB
        "backupCount": 5,
        "formatter": "verbose",
    }
except Exception:
    # If whatsapp_file handler can't be created, use console only
    pass

# Determine which handlers to use for sync loggers
sync_handlers = ["console"]
if "sync_file" in handlers:
    sync_handlers.insert(0, "sync_file")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": handlers,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"] if "file" in handlers else ["console"],
            "level": "ERROR",
            "propagate": True
        },
        "orders.api_client": {
            "handlers": sync_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "orders.management.commands.sync_delivery_orders": {
            "handlers": sync_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "orders.views": {
            "handlers": ["whatsapp_file", "console"] if "whatsapp_file" in handlers else ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}