# Generated by Django 5.1.6 on 2025-02-28 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Warehouse", "Warehouse"),
                            ("Security", "Security"),
                            ("Salesman", "Salesman"),
                            ("Driver", "Driver"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("do_number", models.CharField(max_length=100, unique=True)),
                ("date", models.DateField()),
                ("customer_code", models.CharField(max_length=255)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("salesman", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "salesman_mobile",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("area", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "driver",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Driver1", "Driver 1"),
                            ("Driver2", "Driver 2"),
                            ("Driver3", "Driver 3"),
                            ("Driver4", "Driver 4"),
                            ("Driver5", "Driver 5"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Loaded", "Loaded"),
                            ("Delivered", "Delivered"),
                            ("Partial Delivery", "Partial Delivery"),
                            ("Out for Delivery", "Out for Delivery"),
                            ("Pending", "Pending"),
                            ("Not Delivered", "Not Delivered"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("delivery_date", models.DateTimeField(blank=True, null=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.vehicle",
                    ),
                ),
            ],
        ),
    ]
