# Generated by Django 5.1.6 on 2025-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryorder",
            name="driver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Usman", "Usman"),
                    ("Acharuddin ", "Acharuddin"),
                    ("Fakheer", "Fakheer"),
                    ("Nizar", "Nizar"),
                    ("Sayyam", "Sayyam"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
