# Generated by Django 4.0.6 on 2025-03-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_deliveryorder_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItemWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(max_length=100)),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='driver',
            field=models.CharField(blank=True, choices=[('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam')], max_length=20, null=True),
        ),
    ]
