# Generated by Django 5.1.6 on 2025-03-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_deliveryitemwise_alter_deliveryorder_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Loaded", "Loaded"),
                    ("Delivered", "Delivered"),
                    ("Partial Delivery", "Partial Delivery"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Pending", "Pending"),
                    ("Not Delivered", "Not Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Warehouse", "Warehouse"),
                    ("Security", "Security"),
                    ("Salesman", "Salesman"),
                    ("Driver", "Driver"),
                    ("Junaid Admin", "Junaid Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
