# Generated by Django 4.0.6 on 2025-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_deliveryorder_status_alter_role_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('message_id', models.CharField(max_length=200)),
                ('text_body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
