# Generated by Django 4.0.6 on 2025-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_customerreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('recipient_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
