# Generated by Django 4.0.6 on 2025-04-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliveryorder_lpo_alter_deliveryorder_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreply',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_media/'),
        ),
        migrations.AddField(
            model_name='customerreply',
            name='media_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
