# Generated by Django 4.0.6 on 2025-04-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_customerreply_media_file_customerreply_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreply',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='customerreply',
            name='media_type',
        ),
    ]
