# Generated by Django 4.0.6 on 2025-04-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_customerreply_media_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('driver', models.CharField(blank=True, choices=[('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='orders.vehicle')),
            ],
        ),
    ]
