# Generated by Django 4.0.6 on 2025-04-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_transferorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit_limit', models.PositiveIntegerField(default=120)),
                ('credit_limit_amount', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='driver',
            field=models.CharField(blank=True, choices=[('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam'), ('Customer', 'Customer'), ('Mukarram', 'Mukarram')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warehouse', 'Warehouse'), ('Security', 'Security'), ('Salesman', 'Salesman'), ('Driver', 'Driver'), ('Junaid Admin', 'Junaid Admin'), ('Accounts', 'Accounts'), ('Manager', 'Manager'), ('Collection', 'Collection')], max_length=20),
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('exceeded_days', models.IntegerField(default=0)),
                ('status_of_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('customer_cheque_date', models.DateField(blank=True, null=True)),
                ('payment_received', models.BooleanField(default=False)),
                ('delivery_order', models.OneToOneField(db_column='invoice_number', on_delete=django.db.models.deletion.CASCADE, related_name='credit_payment', to='orders.deliveryorder', to_field='invoice_number')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customer'),
        ),
    ]
