# Generated by Django 4.0.6 on 2025-05-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_customer_deliveryorder_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
