# Generated by Django 4.0.6 on 2025-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_customer_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_terms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
