# Generated by Django 4.0.6 on 2025-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_customer_additional_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='use_next_month_start',
            field=models.BooleanField(default=False),
        ),
    ]
