# Generated by Django 4.0.6 on 2025-05-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_customer_use_next_month_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
