# Generated by Django 4.0.6 on 2025-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_customer_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('Loaded', 'Loaded'), ('Delivered', 'Delivered'), ('Partial Delivery', 'Partial Delivery'), ('Out for Delivery', 'Out for Delivery'), ('Pending', 'Pending'), ('Not Delivered', 'Not Delivered'), ('Cancelled', 'Cancelled'), ('Received by A/c', 'Received by A/c'), ('GRV', 'GRV'), ('On Hold', 'On Hold')], default='Pending', max_length=20),
        ),
    ]
