# Generated by Django 4.0.6 on 2025-06-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_deliveryorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='credit_note',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
