# Generated by Django 4.0.6 on 2025-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_deliveryorder_credit_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEnteredDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_number', models.CharField(max_length=100, unique=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
