# Generated by Django 4.0.6 on 2025-07-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_preentereddo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
