# Generated by Django 4.0.6 on 2025-07-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_creditbulkrequest_creditpayment_bulk_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='orders.customer'),
        ),
    ]
