# Generated by Django 4.0.6 on 2025-07-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_deliveryorder_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedCustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_every_month', models.IntegerField(default=0)),
                ('customer_ids', models.JSONField(default=list)),
            ],
        ),
    ]
