# Generated by Django 4.0.6 on 2025-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_cachedcustomerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='frequency_last_3_months',
            field=models.IntegerField(default=0),
        ),
    ]
