# Generated by Django 4.0.6 on 2025-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_customer_frequency_last_3_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='driver',
            field=models.CharField(blank=True, choices=[('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam'), ('Customer', 'Customer'), ('Mukarram', 'Mukarram'), ('Shaban', 'Shaban')], max_length=20, null=True),
        ),
    ]
