# Generated by Django 4.0.6 on 2025-09-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_deliveryorder_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='driver',
            field=models.CharField(blank=True, choices=[('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam'), ('Customer', 'Customer'), ('Mukarram', 'Mukarram'), ('Shaban', 'Shaban'), ('Ameen', 'Ameen')], max_length=20, null=True),
        ),
    ]
