# Generated by Django 5.2.3 on 2025-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_deliveryorder_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='driver',
            field=models.CharField(blank=True, choices=[('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam'), ('Customer', 'Customer'), ('Mukarram', 'Mukarram'), ('Shaban', 'Shaban'), ('Ameen', 'Ameen'), ('Zubair', 'Zubair')], max_length=20, null=True),
        ),
    ]
