# Generated by Django 4.2.25 on 2025-10-23 06:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_deliveryorder_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPInvoiceUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('rows_ingested', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SAPInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('salesman', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('cancelled', models.BooleanField(default=False)),
                ('document_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.sapinvoiceuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='orders_sapi_date_32392c_idx'), models.Index(fields=['customer_name'], name='orders_sapi_custome_639d2e_idx'), models.Index(fields=['salesman'], name='orders_sapi_salesma_0b51c6_idx')],
            },
        ),
    ]
