# Generated by Django 4.2.25 on 2025-10-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_sapinvoiceuploadbatch_sapinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPCreditNoteUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('rows_ingested', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SAPCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('document_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.sapcreditnoteuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'customer_name'], name='orders_sapc_date_0e995c_idx')],
            },
        ),
    ]
