# Generated by Django 4.2.25 on 2025-10-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_sapcreditnoteuploadbatch_sapcreditnote'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sapcreditnote',
            name='orders_sapc_date_0e995c_idx',
        ),
        migrations.AddField(
            model_name='sapcreditnote',
            name='salesman',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sapcreditnote',
            name='number',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AddIndex(
            model_name='sapcreditnote',
            index=models.Index(fields=['date', 'customer_name', 'salesman'], name='orders_sapc_date_437c26_idx'),
        ),
    ]
