# Generated by Django 5.2.3 on 2025-10-28 12:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_remove_sapcreditnote_orders_sapc_date_0e995c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPCreditUploadGPPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('salesman', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('gp_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_pairs', to='orders.sapcreditnoteuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_name', 'salesman'], name='orders_sapc_custome_11aaf9_idx')],
                'unique_together': {('upload_batch', 'customer_name', 'salesman')},
            },
        ),
    ]
