# Generated by Django 5.2.3 on 2025-10-28 12:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_sapcredituploadgppair'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPCreditUploadGPLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('salesman', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('gp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('upload_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp_lines', to='orders.sapcreditnoteuploadbatch')),
            ],
        ),
        migrations.DeleteModel(
            name='SAPCreditUploadGPPair',
        ),
        migrations.AddIndex(
            model_name='sapcredituploadgpline',
            index=models.Index(fields=['date', 'customer_name', 'salesman'], name='orders_sapc_date_008044_idx'),
        ),
    ]
