# Generated by Django 5.2.3 on 2025-11-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_sapcredituploadgppair'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPUnifiedUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('rows_invoices', models.IntegerField(default=0)),
                ('rows_credits', models.IntegerField(default=0)),
                ('rows_gp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
