# Generated by Django 5.2.3 on 2025-11-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_sapunifieduploadbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapinvoice',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
