# Generated by Django 5.2.3 on 2025-11-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_sapinvoice_customer_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAPUnifiedUploadBatch',
        ),
    ]
