# Generated by Django 5.2.3 on 2025-11-03 05:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_delete_sapunifieduploadbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Credit', 'Credit')], max_length=16)),
                ('number', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('customer_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('salesman', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('item_code', models.CharField(db_index=True, max_length=128)),
                ('item_desc', models.CharField(blank=True, default='', max_length=512)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cr_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lines', to='orders.sapcreditnoteuploadbatch')),
                ('inv_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_lines', to='orders.sapinvoiceuploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'item_code'], name='orders_saps_date_bb5e69_idx'), models.Index(fields=['salesman', 'item_code'], name='orders_saps_salesma_1eba4d_idx')],
            },
        ),
    ]
