# Generated by Django 5.2.3 on 2025-11-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_sapsalesline'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sapcredituploadgpline',
            name='orders_sapc_date_008044_idx',
        ),
        migrations.AddField(
            model_name='sapcredituploadgpline',
            name='customer_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='sapcredituploadgpline',
            index=models.Index(fields=['date', 'customer_code', 'customer_name', 'salesman'], name='orders_sapc_date_9da0ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='sapcredituploadgpline',
            constraint=models.UniqueConstraint(fields=('date', 'customer_code', 'customer_name', 'salesman'), name='uq_gp_day_code_cust_salesman'),
        ),
    ]
