# Generated by Django 5.2.3 on 2025-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_remove_sapcredituploadgpline_orders_sapc_date_008044_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sapsalesline',
            constraint=models.UniqueConstraint(fields=('doc_type', 'number', 'item_code'), name='uniq_doc_type_number_item_code'),
        ),
    ]
