# Generated by Django 5.2.3 on 2025-11-04 15:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_sapsalesline_uniq_doc_type_number_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPItemTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=128, unique=True)),
                ('total_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
