# Generated by Django 5.2.3 on 2025-11-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_sapitemtotals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAPItemTotals',
        ),
    ]
