# Generated by Django 5.2.3 on 2025-11-05 06:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_delete_sapitemtotals'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAPFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Credit', 'Credit')], max_length=16)),
                ('number', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('customer_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('customer_name', models.CharField(db_index=True, max_length=255)),
                ('salesman', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('item_code', models.CharField(db_index=True, max_length=128)),
                ('item_desc', models.CharField(blank=True, default='', max_length=512)),
                ('item_mfr', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18)),
                ('net_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('row_idx', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'salesman'], name='orders_sapf_date_069c4d_idx'), models.Index(fields=['date', 'item_code'], name='orders_sapf_date_fd44ce_idx'), models.Index(fields=['customer_name', 'salesman'], name='orders_sapf_custome_56b339_idx')],
                'unique_together': {('number', 'item_code', 'row_idx')},
            },
        ),
    ]
