# Generated by Django 5.2.3 on 2026-02-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_customer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='driver',
            field=models.CharField(blank=True, choices=[('Default', 'Default'), ('Usman', 'Usman'), ('Acharuddin', 'Acharuddin'), ('Fakheer', 'Fakheer'), ('Nizar', 'Nizar'), ('Sayyam', 'Sayyam'), ('Customer', 'Customer'), ('Mukarram', 'Mukarram'), ('Shaban', 'Shaban'), ('Ameen', 'Ameen'), ('Qasim', 'Qasim'), ('SALESMAN', 'SALESMAN'), ('Rental', 'Rental')], max_length=20, null=True),
        ),
    ]
