# Generated by Django 5.2.3 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_deliveryorder_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
